// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onbptdcfrzofirecfrdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uYnB0ZGNmcnpvZmlyZWNmcmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzE5MjIsImV4cCI6MjA2MjM0NzkyMn0.6iUz4nQ4OQ05szeo2EP2h78Rw7VzkVq9w6-oyiDyGH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);